#!/usr/bin/bash -eu

#-----------------------------------------------------------------------------
function usage () {
    echo "$(basename $0) <Dockerfile directory> (<DockerHub account name>)" 2>&1;
}

#-----------------------------------------------------------------------------
# 任意のイメージをビルドする
# $1 : Dockerfile のあるディレクトリ
# $2 : アカウント名
#-----------------------------------------------------------------------------

DOCKER_BULDKIT=1

EXEC_DIR=$(cd $(dirname $0) && pwd)

set +eu
IMAGE_DIR=$1
ACCOUNT=$2
set -eu

if [ ! -d "${EXEC_DIR}/${IMAGE_DIR}" ]; then
    echo -e "ERROR: No such directory : ${IMAGE_DIR}\n" >&2;
    usage
    echo -e "\nPlease select a directory from the following list:"
    ls -1F | grep -E "^.+\/$" | sed -E "s|(.+)/$|    \1|g"
    exit 1
fi

if [ -n "${ACCOUNT}" ]; then
    ACCOUNT="${ACCOUNT}/"
    TAG="${2}/${1}"
else
    TAG="${1}"
fi

docker login

NUM_OF_LOGICAL_PROCESSORS=$(grep processor /proc/cpuinfo | wc -l)
CPU_CORES=0-$((${NUM_OF_LOGICAL_PROCESSORS} - 1))
MEM_LIMIT_GB=$(free -g | sed -n 2p | awk '{ print $7 }')

docker builder build \
    --tag         "${TAG}:latest" \
    --cpuset-cpus "${CPU_CORES}" \
    --memory      "${MEM_LIMIT_GB}G" \
    --progress    plain \
    --file        "${EXEC_DIR}/${IMAGE_DIR}/Dockerfile" \
    --build-arg   ACCOUNT=${ACCOUNT} \
    --build-arg   USERNAME=$(whoami) \
    "${EXEC_DIR}/${IMAGE_DIR}"

