#!/usr/bin/bash -eu

#-----------------------------------------------------------------------------
function usage () {
echo -e "
使い方: container-login [OPTION] TAG
cli-enhanced の新しいコンテナを実行しログインします。
例: container-login -u 'user' brew-base

\e[33;1m引数:
    \e[32mTAG
        \e[37mイメージタグを指定します。
        DockerHub のアカウント名を使用する形式（'account/cli-enhanced'）
        もしくはタグ名のみの形式（'cli-enhanced'）を指定することができます。

\e[33;1mオプション:
    \e[32m-u\e[37m, \e[32m--user <ユーザー名>
        \e[37m省略可。コンテナで使用するユーザー名を指定します。
        省略した場合は、現在のホスト側ユーザー名が指定されます。
    \e[32m-s\e[37m, \e[32m--cred-dir <ユーザー名>
        \e[37mシークレット情報(.secrets)を保持するホスト側のディレクトリを指定します。
    \e[32m-d\e[37m, \e[32m--work-dir <ユーザー名>
        \e[37mホスト側の作業用ディレクトリを指定します。
\e[m
" 2>&1;
}

#-----------------------------------------------------------------------------
# Docker イメージからコンテナを作成しログインする
# $1 : タグ名 = DockerHub アカウント名(省略可）/ Dockerfile のあるディレクトリ
# 例 : xxx/brew-base or brew-base
#-----------------------------------------------------------------------------
EXEC_DIR=$(cd $(dirname $0) && pwd)

if [ $# -eq 0 ]; then
    echo -e "\e[31merror: \e[37m少なくとも1つの引数が必要です。\e[m" >&2;
    usage
    exit 1
fi

VALID_ARGS=$(getopt -o husd: --long help,user:,cred-dir:,work-dir: -- "$@")
# getopt の返り値をチェックして、失敗ならエラー終了
if [[ $? -ne 0 ]]; then
    exit 1;
fi

TAG=
USERNAME=
CREDENTIALS_DIR=
WORKING_DIR=

eval set -- "${VALID_ARGS}"
while [ : ]; do
    case "$1" in
        -u | --user)
            USERNAME=$2
            shift 2
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        -s | --cred-dir)
            CREDENTIALS_DIR=$2
            shift 2
            ;;
        -d | --work-dir)
            WORKING_DIR=$2
            shift 2
            ;;
        --) shift;
            break
            ;;
    esac
done

# 引数が少ない場合
if [ $# -lt 1 ]; then
    echo -e "\e[31merror: \e[37mタグを指定してください。\e[m" >&2;
    usage
    exit 1
# 引数が多すぎる場合
elif [ $# -gt 1 ]; then
    echo -e "\e[31merror: \e[37m引数が多すぎます。\e[m" >&2;
    usage
    exit 1
fi
set +u

TAG=$1
set -u

# 必須のオプションを使用していない場合
if [ -z "${CREDENTIALS_DIR}" ]; then
    echo -e "\e[31merror: \e[37mクレデンシャルディレクトリを指定してください。\e[m" >&2;
    usage
    exit 1
fi

if [ -z "${CREDENTIALS_DIR}" ]; then
    echo -e "\e[31merror: \e[37m作業用ディレクトリを指定してください。\e[m" >&2;
    usage
    exit 1
fi

# ホスト側のディレクトリを指定しているかを判定する
if [ ! -d "${CREDENTIALS_DIR}" ]; then
    echo -e "\e[31merror: \e[37m。ホスト側のクレデンシャルディレクトリが見つかりません。\e[m" >&2;
    usage
    exit 1
fi

# ホスト側のディレクトリが存在しない場合は、ディレクトリを作成する
if [ ! -d "${WORKING_DIR}" ]; then
    echo -e "\e[31merror: \e[37m。ホスト側の作業用ディレクトリが見つかりません。\e[m" >&2;
    usage
    exit 1
fi

# ユーザーが省略されている場合
if [ -z "${USERNAME}" ]; then
    # イメージのビルド時に指定したユーザーを取得
    if [ -e "${EXEC_DIR}/.user" ]; then
        USERNAME=$(cat ${EXEC_DIR}/.user)
    else
        USERNAME=$(whoami)
        # 次回、ユーザーを省略できるようにファイルを出力
        echo "${USERNAME}" > ${EXEC_DIR}/.user
    fi
fi

NUM_OF_LOGICAL_PROCESSORS=$(grep processor /proc/cpuinfo | wc -l)
CPU_CORES=0-$((${NUM_OF_LOGICAL_PROCESSORS} - 1))
MEM_LIMIT_GB=$(free -g | sed -n 2p | awk '{ print $7 }')

docker run \
    --interactive \
    --tty \
    --cpuset-cpus        "${CPU_CORES}" \
    --memory             "${MEM_LIMIT_GB}G" \
    --memory-reservation "${MEM_LIMIT_GB}G" \
    --entrypoint         bash \
    --user               "${USERNAME}:${USERNAME}" \
    --mount type=bind,source="${CREDENTIALS_DIR}",target="/var/credentials" \
    --mount type=bind,source="${WORKING_DIR}",target="/home/${USERNAME}/Documents" \
    "${TAG}"
    